### ISSUE TITLE
Not working in RF 4.4

### ISSUE THREAD

**Issue by ninastoessinger** [sansplomb/QuadraticConverter#7]
Hi there,

Thanks so much for making QuadraticConverter! 
FYI in the new version of RoboFont (v.4.4) I have not had success in getting QuadraticConverter v.0.8.1 to work. Looks like maybe the way to reference segment types has changed? See error message below, this appears when I hit “convert font”. Many thanks if you have a chance to take a look, I know everyone’s time is limited. :)

```
Traceback (most recent call last):
  File "/Applications/RoboFont.app/Contents/Resources/lib/python3.9/vanilla/vanillaBase.py", line 520, in action_
    self.callback(sender)
  File "QuadraticConverter.py", line 835, in convertCurrentFontCallback
  File "/Applications/RoboFont.app/Contents/Resources/lib/python3.9/fontParts/base/lib.py", line 157, in __getitem__
    return super(BaseLib, self).__getitem__(key)
  File "/Applications/RoboFont.app/Contents/Resources/lib/python3.9/fontParts/base/base.py", line 346, in __getitem__
    value = self._getItem(key)
  File "/Applications/RoboFont.app/Contents/Resources/lib/python3.9/fontParts/fontshell/lib.py", line 20, in _getItem
    return self.naked()[key]
KeyError: 'com.typemytype.robofont.segmentType'
Traceback (most recent call last):
  File "lib/doodleDelegate.pyc", line 89, in sendEvent_
  File "/Applications/RoboFont.app/Contents/Resources/lib/python3.9/vanilla/vanillaBase.py", line 520, in action_
    self.callback(sender)
  File "QuadraticConverter.py", line 835, in convertCurrentFontCallback
  File "/Applications/RoboFont.app/Contents/Resources/lib/python3.9/fontParts/base/lib.py", line 157, in __getitem__
    return super(BaseLib, self).__getitem__(key)
  File "/Applications/RoboFont.app/Contents/Resources/lib/python3.9/fontParts/base/base.py", line 346, in __getitem__
    value = self._getItem(key)
  File "/Applications/RoboFont.app/Contents/Resources/lib/python3.9/fontParts/fontshell/lib.py", line 20, in _getItem
    return self.naked()[key]
KeyError: 'com.typemytype.robofont.segmentType'
```

**Comment by ninastoessinger** [comment]
Nevermind I think, with the next project it works again. Not sure what happened!
